#!/usr/bin/env bash

function toggle_menu {
    hyprctl keyword blurls "remove,gtk-layer-shell"
    STATE=$(eww active-windows | grep $1 | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE ]]; then
        if [[ $1 == 'powermenu' ]]; then hyprctl keyword blurls "remove,gtk-layer-shell"; fi
        eww close $1;
    else
        if [[ $1 == 'powermenu' ]]; then hyprctl keyword blurls "gtk-layer-shell"; fi
        eww open $1;
    fi
}

function network {
    nm-connection-editor
}

function screenlock {
    STATE0=$(eww active-windows | grep powermenu0 | awk '{print substr ($0, 0, 1)}')
    STATE1=$(eww active-windows | grep powermenu1 | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE0 ]]; then eww close powermenu0; fi
    if [[ $STATE1 ]]; then eww close powermenu1; fi

    hyprctl keyword blurls "gtk-layer-shell"
    swaylock -e -f -i $HOME/.dotfiles/wallpaper/Desktop/mountains-1412683.jpg
}

if [[ $1 == 'pavu'           ]]; then pavucontrol; fi
if [[ $1 == 'network'        ]]; then network; fi
if [[ $1 == 'brightness'     ]]; then wl-gammactl; fi
if [[ $1 == 'bluetooth'      ]]; then bluedevil-wizard; fi
if [[ $1 == 'powermenu'      ]]; then powermenu; fi
if [[ $1 == 'toggle_menu'    ]]; then toggle_menu $2; fi
if [[ $1 == 'close_calendar' ]]; then close_calendar; fi
if [[ $1 == 'screenlock'     ]]; then screenlock; fi
