#!/usr/bin/env bash

function toggle_menu {
    MAIN=$(eww get main_monitor)
    hyprctl keyword blurls "remove,gtk-layer-shell"
    STATE=$(eww windows | grep $1$MAIN | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE == '*' ]]; then
        if [[ $1 == 'powermenu' ]]; then hyprctl keyword blurls "remove,gtk-layer-shell"; fi
        eww close $1$MAIN;
    else
        if [[ $1 == 'powermenu' ]]; then hyprctl keyword blurls "gtk-layer-shell"; fi
        eww open $1$MAIN;
    fi
}

function network {
    nm-connection-editor
}

function screenlock {
    STATE0=$(eww windows | grep powermenu0 | awk '{print substr ($0, 0, 1)}')
    STATE1=$(eww windows | grep powermenu1 | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE0 == '*' ]]; then eww close powermenu0; fi
    if [[ $STATE1 == '*' ]]; then eww close powermenu1; fi

    hyprctl keyword blurls "gtk-layer-shell"
    swaylock -f -c 000000
}

if [[ $1 == 'pavu'           ]]; then pavucontrol; fi
if [[ $1 == 'network'        ]]; then network; fi
if [[ $1 == 'brightness'     ]]; then wl-gammactl; fi
if [[ $1 == 'bluetooth'      ]]; then blueberry; fi
if [[ $1 == 'powermenu'      ]]; then powermenu; fi
if [[ $1 == 'toggle_menu'    ]]; then toggle_menu $2; fi
if [[ $1 == 'close_calendar' ]]; then close_calendar; fi
if [[ $1 == 'picker'         ]]; then picker; fi
if [[ $1 == 'screenlock'     ]]; then screenlock; fi

# if [[ $1 == 'firefox'       ]]; then flatpak run org.mozilla.firefox; fi
# if [[ $1 == 'terminal'      ]]; then wezterm; fi
# if [[ $1 == 'file-manager'  ]]; then gtk-launch org.gnome.Nautilus; fi
# if [[ $1 == 'editor'        ]]; then wezterm start $EDITOR; fi
# if [[ $1 == 'spotify'       ]]; then flatpak run com.spotify.Client; fi
# if [[ $1 == 'caprine'       ]]; then flatpak run com.sindresorhus.Caprine; fi
# if [[ $1 == 'bitwig'        ]]; then gtk-launch bitwig; fi
# if [[ $1 == 'battle'        ]]; then gtk-launch Battle; fi
# if [[ $1 == 'bottles'       ]]; then flatpak run com.usebottles.bottles; fi
